### ISSUE TITLE
Diagrama de clase y de secuencia 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-1-1#1]
[Reporte diagrmas .pdf](https://github.com/user-attachments/files/18043752/Reporte.diagrmas.pdf)

**Comment by Ariadnamonserrat10** [comment]
29 de 30 cumple con las caracteristicas mencionadas en la rubrica y se expresa claramente la descripcion de los procesos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
